import Link from "next/link";

export const metadata = { title: "Terms of Service — TrueTwist" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-dark-bg">
      <div className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
            Terms of Service
          </h1>
          <p className="text-sm text-gray-400 dark:text-dark-muted mb-12">
            Last updated: April 8, 2026
          </p>

          <div className="prose prose-gray dark:prose-invert max-w-none space-y-8 text-gray-600 dark:text-dark-muted text-sm leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using TrueTwist (&quot;the Platform&quot;), you
                agree to be bound by these Terms of Service. If you do not agree
                to these terms, do not use the Platform. We may update these
                terms from time to time, and your continued use constitutes
                acceptance of any changes.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                2. Description of Service
              </h2>
              <p>
                TrueTwist is an AI-powered social media management platform that
                provides content creation, scheduling, analytics, ad
                optimization, and related services. Features may vary by
                subscription plan and may change over time.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                3. Account Registration
              </h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>You must be at least 18 years old to create an account.</li>
                <li>
                  You are responsible for maintaining the confidentiality of
                  your account credentials.
                </li>
                <li>
                  You are responsible for all activities that occur under your
                  account.
                </li>
                <li>
                  You must provide accurate and complete information during
                  registration.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                4. Acceptable Use
              </h2>
              <p className="mb-3">You agree not to:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  Use the Platform to generate or distribute spam, misleading
                  content, or content that violates any social media
                  platform&apos;s terms of service.
                </li>
                <li>
                  Attempt to reverse-engineer, decompile, or extract source code
                  from the Platform.
                </li>
                <li>
                  Use the Platform in any way that violates applicable laws or
                  regulations.
                </li>
                <li>
                  Share your account credentials or allow unauthorized access to
                  your account.
                </li>
                <li>
                  Use the AI content generation features to create harmful,
                  defamatory, or illegal content.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                5. AI-Generated Content
              </h2>
              <p>
                Content generated by our AI tools is provided as suggestions.
                You are solely responsible for reviewing, editing, and approving
                any AI-generated content before publishing. TrueTwist does not
                guarantee the accuracy, originality, or appropriateness of
                AI-generated content, and you assume all liability for content
                you publish.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                6. Intellectual Property
              </h2>
              <p>
                You retain ownership of content you create and upload to the
                Platform. By using our AI tools, you grant us a limited license
                to process your inputs for the purpose of generating content.
                The Platform, its design, features, and underlying technology
                are owned by TrueTwist and protected by intellectual property
                laws.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                7. Subscription & Billing
              </h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  Paid plans are billed on a recurring basis (monthly or
                  annually) as selected at checkout.
                </li>
                <li>
                  You may cancel your subscription at any time. Cancellation
                  takes effect at the end of the current billing period.
                </li>
                <li>
                  We reserve the right to change pricing with 30 days notice.
                </li>
                <li>Refunds are handled on a case-by-case basis.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                8. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by law, TrueTwist shall not be
                liable for any indirect, incidental, special, consequential, or
                punitive damages arising from your use of the Platform. Our
                total liability shall not exceed the amount you paid us in the
                12 months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                9. Termination
              </h2>
              <p>
                We may suspend or terminate your account if you violate these
                Terms. Upon termination, your right to use the Platform ceases
                immediately. We will make your data available for export for 30
                days after termination.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                10. Contact
              </h2>
              <p>
                For questions about these Terms, contact us at{" "}
                <a
                  href="mailto:legal@truetwist.com"
                  className="text-brand-500 hover:text-brand-600"
                >
                  legal@truetwist.com
                </a>
                .
              </p>
            </section>
          </div>

          {/* Back link */}
          <div className="mt-12 pt-8 border-t border-gray-200 dark:border-dark-border">
            <Link
              href="/"
              className="text-brand-500 hover:text-brand-600 font-medium"
            >
              &larr; Back to home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
